### PR TITLE
Update Find duplicate

### PR DESCRIPTION
**Pull request by PranavShekhar30**
Optimal solution would b using Linked Lost Cycle Method. Time complexity becomes O(N) and space complexity becomes O(1).

### CODE REVIEW

**Comment by PranavShekhar30** [comment]
Can u merge this??

**Comment by PranavShekhar30** [comment]
Waiting for ur response from 9 days

**Review by hitsa70 — APPROVED** [review]

**Comment by hitsa70** [comment]
Done sir

**Comment by PranavShekhar30** [comment]
Have u merged it sir? because it is still showing as open in my PR's

**Comment by hitsa70** [comment]
Yes

**Comment by PranavShekhar30** [comment]
Thanks a lot Sir...that's very kind of u. Keep coding :)

**Pull request merged**
